// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvqXUe0BmibuCLX-_DNq675XbN7u4A8jY',
    appId: '1:108641246248:web:a006a785b7afd0c83fa91d',
    messagingSenderId: '108641246248',
    projectId: 'instagram-8d731',
    authDomain: 'instagram-8d731.firebaseapp.com',
    storageBucket: 'instagram-8d731.appspot.com',
    measurementId: 'G-KFRL0P1JQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArCG8tW7YN_9s0rE5gDLc9Ydy0StrumGg',
    appId: '1:108641246248:android:ab6e17dcb9db73173fa91d',
    messagingSenderId: '108641246248',
    projectId: 'instagram-8d731',
    storageBucket: 'instagram-8d731.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj7aYTNulJaJxguiv1wPChth8g9Km1CWA',
    appId: '1:108641246248:ios:57cd85edd4368f8e3fa91d',
    messagingSenderId: '108641246248',
    projectId: 'instagram-8d731',
    storageBucket: 'instagram-8d731.appspot.com',
    iosClientId: '108641246248-oih78nur9bapu06gt11iqflke73v13m0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInsta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj7aYTNulJaJxguiv1wPChth8g9Km1CWA',
    appId: '1:108641246248:ios:57cd85edd4368f8e3fa91d',
    messagingSenderId: '108641246248',
    projectId: 'instagram-8d731',
    storageBucket: 'instagram-8d731.appspot.com',
    iosClientId: '108641246248-oih78nur9bapu06gt11iqflke73v13m0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInsta',
  );
}
